### ISSUE TITLE
Support for gif

### ISSUE THREAD

**Issue by mathewrapid** [digiaonline/cuddly-potato#29]
Got an error when trying to handle a gif
```
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11111
Traceback (most recent call last):
  File "face_replace/face_replace.py", line 288, in <module>
    args.boxes,
  File "face_replace/face_replace.py", line 156, in detect
    gray = cv2.cvtColor(l_img, cv2.COLOR_BGR2GRAY)
cv2.error: /io/opencv/modules/imgproc/src/color.cpp:11111: error: (-215) scn == 3 || scn == 4 in function cvtColor

vagrant@vagrant:/vagrant$ python face_replace/face_replace.py success_kid.jpg
[ INFO:0] Initialize OpenCL runtime...
[[34 40 46 46]]
```

**Comment by hugovk** [comment]
OpenCV doesn't do GIF yet, I think they've just not implemented it yet since the GIF patents expired. Anyway, shouldn't be too hard to do a quick convert first.

**Comment by hugovk** [comment]
It's easy enough to do it in the Python code, I'll send a PR soon.
