### ISSUE TITLE
John Malkovich bug with force photobomb

### ISSUE THREAD

**Issue by mathewrapid** [digiaonline/cuddly-potato#42]
https://files.slack.com/files-pri/T047BAY1N-FAFAGHNSY/image.png

force `bomb` yields this error:
```
2018/04/30 11:01:40 Traceback (most recent call last):
  File "/home/ubuntu/cuddly-potato/face_replace/face_replace.py", line 325, in <module>
    img = photobomb(args.infile, args.bodies)
  File "/home/ubuntu/cuddly-potato/face_replace/face_replace.py", line 157, in photobomb
    s_img = image_resize(s_img, width=int(l_img.shape[1] * 0.5))
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by hugovk** [comment]
Reproducible with:
```
python face_replace.py ~/Downloads/image.png -p -b /Users/hugo/github/cuddly-potato/face_replace/data/bodies/chuck3.png
```

**Comment by hugovk** [comment]
Actually, only reproducible with that after I had moved the image from ~/Downloads/image.png. 

I'll add some input filename validation to help debug.

**Comment by hugovk** [comment]
Done in https://github.com/digiaonline/cuddly-potato/pull/43.
